POST  http://localhost:8080/events
content-type: application/json
authorization: <JWT_TOKEN>

{
    "name": "Test event",
    "description": "Test descr",
    "location": "test location",
    "dateTime": "2026-01-01T15:30:00.000Z"
}