PUT  http://localhost:8080/events/6
content-type: application/json
authorization: <JWT_TOKEN>

{
    "name": "Test event upd",
    "description": "Test descr upd2",
    "location": "test location upd",
    "dateTime": "2026-01-01T15:30:00.000Z"
}