PUT  http://localhost:8080/events/6
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzY5MjA4NjcwLCJ1c2VySWQiOjJ9.kK4nLlCbpG6TCCqT2BTsZJ_Gk-ptl4z1wSOO1Kt7KD4

{
    "name": "Test event upd",
    "description": "Test descr upd2",
    "location": "test location upd",
    "dateTime": "2026-01-01T15:30:00.000Z"
}